language: ruby
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.1
  - ruby-head

before_install:
  - gem install bundler -v '< 2'

cache: bundler

script: bundle exec rake

notifications:
  email: false

git:
  depth: 10

matrix:
  allow_failures:
    - rvm: ruby-head
